from tortoise import BaseDBAsyncClient

RUN_IN_TRANSACTION = True


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        ALTER TABLE "collect_logs_sources" DROP CONSTRAINT IF EXISTS "collect_logs_sources_collect_logs_id_fkey";
        ALTER TABLE "collect_logs_sources" DROP CONSTRAINT IF EXISTS "collect_logs_sources_pkey";
        ALTER TABLE "collect_logs" DROP CONSTRAINT IF EXISTS "collect_logs_pkey";
        ALTER TABLE "collect_logs_sources" RENAME COLUMN "collect_logs_id" TO "collect_logs_uuid_id";
        ALTER TABLE "collect_logs" RENAME COLUMN "id" TO "uuid_id";
        ALTER TABLE "collect_logs_sources" RENAME COLUMN "id" TO "uuid_id";
        ALTER TABLE "collect_logs" ADD COLUMN "id" BIGINT GENERATED BY DEFAULT AS IDENTITY;
        ALTER TABLE "collect_logs_sources" ADD COLUMN "id" BIGINT GENERATED BY DEFAULT AS IDENTITY;
        ALTER TABLE "collect_logs_sources" ADD COLUMN "collect_logs_id" BIGINT;
        UPDATE "collect_logs_sources" AS source
        SET "collect_logs_id" = logs."id"
        FROM "collect_logs" AS logs
        WHERE source."collect_logs_uuid_id" = logs."uuid_id";
        ALTER TABLE "collect_logs" ALTER COLUMN "id" SET NOT NULL;
        ALTER TABLE "collect_logs_sources" ALTER COLUMN "id" SET NOT NULL;
        ALTER TABLE "collect_logs_sources" ALTER COLUMN "collect_logs_id" SET NOT NULL;
        ALTER TABLE "collect_logs" ADD PRIMARY KEY ("id");
        ALTER TABLE "collect_logs_sources" ADD PRIMARY KEY ("id");
        ALTER TABLE "collect_logs_sources"
            ADD CONSTRAINT "collect_logs_sources_collect_logs_id_fkey"
            FOREIGN KEY ("collect_logs_id") REFERENCES "collect_logs" ("id") ON DELETE CASCADE;
        ALTER TABLE "collect_logs_sources" DROP COLUMN "collect_logs_uuid_id";
        ALTER TABLE "collect_logs" DROP COLUMN "uuid_id";
        ALTER TABLE "collect_logs_sources" DROP COLUMN "uuid_id";
        COMMENT ON COLUMN "collect_logs"."id" IS 'Database-generated integer id for this collected log artifact.';
        COMMENT ON COLUMN "collect_logs_sources"."id" IS 'Database-generated integer id for this collected source metadata row.';
        COMMENT ON COLUMN "collect_logs_sources"."file" IS 'Logs-root-relative source file path, for example sessions/<session_id>/<project_name>/<source>.log or workflow/<project_name>/latest/<source>.log.';"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE EXTENSION IF NOT EXISTS "pgcrypto";
        ALTER TABLE "collect_logs_sources" DROP CONSTRAINT IF EXISTS "collect_logs_sources_collect_logs_id_fkey";
        ALTER TABLE "collect_logs_sources" DROP CONSTRAINT IF EXISTS "collect_logs_sources_pkey";
        ALTER TABLE "collect_logs" DROP CONSTRAINT IF EXISTS "collect_logs_pkey";
        ALTER TABLE "collect_logs" ADD COLUMN "uuid_id" UUID NOT NULL DEFAULT gen_random_uuid();
        ALTER TABLE "collect_logs_sources" ADD COLUMN "uuid_id" UUID NOT NULL DEFAULT gen_random_uuid();
        ALTER TABLE "collect_logs_sources" ADD COLUMN "collect_logs_uuid_id" UUID;
        UPDATE "collect_logs_sources" AS source
        SET "collect_logs_uuid_id" = logs."uuid_id"
        FROM "collect_logs" AS logs
        WHERE source."collect_logs_id" = logs."id";
        ALTER TABLE "collect_logs_sources" ALTER COLUMN "collect_logs_uuid_id" SET NOT NULL;
        ALTER TABLE "collect_logs_sources" DROP COLUMN "collect_logs_id";
        ALTER TABLE "collect_logs_sources" DROP COLUMN "id";
        ALTER TABLE "collect_logs" DROP COLUMN "id";
        ALTER TABLE "collect_logs_sources" RENAME COLUMN "collect_logs_uuid_id" TO "collect_logs_id";
        ALTER TABLE "collect_logs_sources" RENAME COLUMN "uuid_id" TO "id";
        ALTER TABLE "collect_logs" RENAME COLUMN "uuid_id" TO "id";
        ALTER TABLE "collect_logs" ADD PRIMARY KEY ("id");
        ALTER TABLE "collect_logs_sources" ADD PRIMARY KEY ("id");
        ALTER TABLE "collect_logs_sources"
            ADD CONSTRAINT "collect_logs_sources_collect_logs_id_fkey"
            FOREIGN KEY ("collect_logs_id") REFERENCES "collect_logs" ("id") ON DELETE CASCADE;
        COMMENT ON COLUMN "collect_logs"."id" IS 'Unique UUID for this collected log artifact.';
        COMMENT ON COLUMN "collect_logs_sources"."id" IS 'Unique UUID for this collected source metadata row.';
        COMMENT ON COLUMN "collect_logs_sources"."file" IS 'Persisted source file path under logs root, when collection succeeded.';"""


MODELS_STATE = (
    "eJztXVtv47YS/iuEX3YLZNNc9naKokBu26bdTYLEOVu0KAxaom02EqWSVBy32P/eGYq6S4"
    "7lOLayzUtgkRxqNJ+GM5wZKv/0/MBlnto+GDOhj6jn9b4j//QE9Rn8qHZukR4Nw6wLGzQd"
    "emY0xWEDB8aZdjpUWlJHQ9eIeopBk8uUI3moeSCQ4FwwEjKpuNLMJZ+OLoiZguAUJJDED2"
    "4ZmXI94YJQophSQLiNc7uBA5NzMX7YNJHgf0VsoIMx0xMmYbLf/4BmLlx2x1RyGd4MRpx5"
    "bkE03MUJTPtAz0LTdn19evzBjEQWhwMn8CJfZKPDmZ4EIh0eRdzdRhrsA46ZpPAAOXGJyP"
    "OscJOmmGNo0DJiKatu1uCyEY08FHrv+1EkHJQ1MXfCP69/6FVhuDZzEuSEjEBeIChFJHMC"
    "6Vp5GknKYFqRPXIITU4gEGsuNArtny/x42fCMa09vNfRTweXL/fffmPEESg9lqbTiK73xR"
    "BSTWNSA0AmcUcylM+A6qrkj6FHc5/VS79IWULBtaTbyY9l0EgaMjiyVz7Bw8qqLPz+EcG7"
    "Kk39kEwnTMTyz4udTKki9iEWhKAHo91z4c3smzEHkv7pp5Or/sGnC5zZV+ovz0j0oH+CPX"
    "umdVZqfRkjGIB+x7qfTkI+n/Z/InhJfjs/OynjnI7r/9ZDnmikg4EIpgPq5l7ipDWRI4zM"
    "3gOrwIN2GlikWqUmLo89YPwqvVusf2pCJfwezojFXsHrQDUZMi8QY6IDEsBqF69vTQvi6p"
    "WyKnwGD1sj/8Mg8BgV8yFIaUsoDIH4sQBosECfJ2bht0seaJpP5Q2KnBHgkgQj87MobnLh"
    "USEAJMcLFBvEVs92EhWFYSA1mBuAbyq5ZvHc7C70uMO1N3s4XIfn5x8Lunp42i9q49n1p8"
    "OTy5e7BlEYBGxg8+lZvwTnNIDHDanDqlAewZt4IiLfYHkKvFERDytgWpighCc8znr16ZLB"
    "DMYJ8IIxSVmzRo2Z9fQ78gI7Rl4wfWE6rMYpZ8LcyINfSTcBRDS70+hCvLD4xiRUEICJoX"
    "PDwbXg4hbuysdUL66NPZ/eDTwmxnoCl+/noP3/g0ujn+9LK+6Z7djDniKq7BZeyWURTYk3"
    "jaZx5GL/BXnYAt1yJgQsoe+ExssEvy0AOrxEawd/VBBJh8VNHriDZoTaMk5gnmjA7hwWLg"
    "3X3v4CeO3tNwKGXUXEHI/jKlJn0hC1BrcmT7QUWtbcrgCsgwgUTGjuGFP2gSptHBjDIeFu"
    "QQWZ3IodHXpLuWFlORTevFkEhjdvmnHAvlogjBjbQ5GQbRiMnz/3SY4j+E25DyggQKMZRz"
    "8ihYIgYuNAzlaCye7eIksZjGrExPQVMTEaay5aIFIg2jAeqArID0F+YjGbVdZushTsSk03"
    "ItIdVYgkrwq8DwaxXuB2eAdEndgBcn15Wi/tdATajcyw0Mz2qxt04GCCbdIHaF45qTsO/u"
    "1t4tT5oV6BP9c/+bVf8OcSWF5+Ovj1m8L+6+P52Y/J8ByMRx/PD0vouZE0/gh4psCJq6pQ"
    "fvAC2oBlHXEJ2BFSrxdaRlWErprBImERvC9iubQrGOymcYkDfNquZXMwOj6/Pvx4Qi4uT4"
    "5Or07Pz4q7YtNZ9LUvTw4+lvdOkeOAG9l215RRrXG/lEaTGrZLsfkAF9kPPYYm37I5gvvO"
    "yEgGfm7nRCOXaxOiC5lxmTu1B2JSBhIE7rayL0WqDa96VyYGSwxPBHky/tYI3n5ABn5J9i"
    "cI3qqO6q6lD2WAjLY29mW6DcNxEbMTm3tN5dhoyHCW6k2CAFEgcADO8o9r1o0IpkvuSh7D"
    "CYjt5OCGzWrWrZ+vzs8aFq0iWQmPawGC+t3ljt4iuE37Y712hAo+gg07sT4AMgkakoQOcH"
    "8/GsXqUoWsDTxz0EDJzTf5Zeu+VQzN4QRlkw8vWuQzvHkLpApEncLpCnDS/O98CiJlFi5D"
    "bZyBkVneQo/OEDmXDaPxGEDpEESYQhrd5FIa2DCkzs2USndQ6Qn2gqax1S5/zy+3UAFG17"
    "VPjM9nk3hHAWz3HP0xGMfPWMrx5bu35mX5nHjgwEtG3pvmu4hzc8RnmmJ2x2CGYez8VIAt"
    "bE5hnmp+bwn6FSf2Dvn4VDT4yrXhFy4qvrFVjIfl9Oo15RiEMqSK5ZIJGJ8cg6eWhl7AtF"
    "hx2fBoo7wbbM0YOXz1v729/f13ezv7b9+/ef3u3Zv3O+9hrHmcate7eQ7c6Y/oihXUKPHN"
    "nnOAdYClr/9zRrBbGcEVRlHziaYsIZ80ZBkN+2ZAo1pr+u/ryhcdpVLMRLtFnEhKgAG2sb"
    "lMUT4H1IUUz0Z3SqtM8iTOeLIFAm88t+4ZB5zPcQ42lyhIeFzGFpVoO2+NsuUms0JogQA0"
    "N3IWNkFPxOQkgppvcwQN1STQA5fLNmHyMt2mFfAiLZxLOCPAGYAdyBkJqZ6QCOaMQ37Gz5"
    "ZBsKgarjvmnbybcEevZlX8AK31oFQIqxppHOzt2Cfdxpku2YiBnXDWrJ0XCIkOUrQGCe/b"
    "fypQT7BTidEaYF2CQBxN13JRvp2914uE+WBYeYGk0pnwW9baQpXpNhzL+5xkhCxfuRyesU"
    "zTrD82USbxEI9d2DV/fHPF1cADcakaWzU3+1Cg61i9Fo8LtWL+aoBIag6sa9GppEMabxws"
    "GWFtnGAFMbylEMuVGw8j7mkOWxO8YV3F8VVt5DUXbQWIhwzwY8RPHETM2XpRi5qddYdfDY"
    "O3D0G0nv7pARo/R5YFTDGkwiVUa8yb29Bt5ll2FNVImJD/4MEKe+9ETwHnrMIynzwxFcpT"
    "8IaICHAnx5Sp+hIF8DuKbw4OLpriGvcuwQnphp2Vc8nHXFCvGBk33KW5k+74JJn8IqG5t5"
    "zoU9JOit5w10HRT6kUwEKrBSxP8xTWqmOmmfS5gG7ukIR7ME86koLl8iJJ6KnztghYl7OB"
    "5mFLvyJP9RSQu0SOyTjiLsaQnxpiLfK95TqLutowS/jhl0vmmYq3GhSrOdzYIVt3aEKaY5"
    "d1WdkYN+s0YJTFnmgC5yFoh13WatfvL2vKmluRzs+dZ3JfLIM+yAH/gEx6XrCgWdwFe//g"
    "9HrLSZ9z7nNz7laa+Szuc+q9i8mO+3F7zr7Xlwi28eCLVJvOgtTUBG4ZJWZ3FCucCVoTJt"
    "wtIsDLvzMnykYSzweKDgV5rUybDy/dn58vTdE1XOKDgFmGHsR+AysuosGXLGR+uwAOZe3K"
    "UHhbOaxkyn3bZAQzis5IO2aJRKoSpcsOy+DpWBApSN9kRCwEJmXY0fRg/mlb4FMi2zRIP0"
    "XgrL5Cc2Jq/v2ShuRGdxQGuDej/tILVEq94YBPLhRqWEo9hExFlHaDyJwfh19Myi6sTyGV"
    "isnWB1xLZJs+YGG4wTCAWXNMoiFVhDQhvoy0H+VYiwikTz3+d3ymznLdRvqNE2wYh7M8Xy"
    "kcxmwMwTgXAnCww/ZmCnO2eCa/O+DYZwT3liu2DDiNE2wYnOO4nxi+KuDABaBjzoJ3Cw9Y"
    "93VUEwhb1Dwk1Ju207ni0pipvN+abS/BOETigUfxdhdBYbcZhN0yBm3rpx6pbGp1uoChuV"
    "dYuQaOE0ZRb4vRLXRai/s9W+urvv0+KxP/4dvv8+WzcBnP8cM2lufnKq/K4+IKlcLwdVdj"
    "eeCpA2BR3XdhGsNsRaL7w22rUqidGksT+UPc6I0IMqVy3/tLQ22xdNvF1PZ2X797/X7/7e"
    "s0lJa2zIugNRwibrOrSAk2fXTYSO2Vx26Zl6/zjc8Sm4BYvHxhuVX7lWrdm4v/SoqsAJss"
    "5svKJdvxOfAOZchq6ujjZEjbPEAN8fpWqY0kwdaXC6ikMesxq3ETAsn4WPzCZhVX7d605V"
    "eFVVPCEpolnaZpsLq3GIQEomFx9ejRwdXRwfFJ78tmDg7brxkkwcFeTQK0PGRrXvoz8Y2S"
    "DXvL3CdmJpP8f7rnx6/7mmozhbFINaEhM1+KS/px5WnOfD5syuePCFsrWf2IsNIBntHPan"
    "ifPyG8xhxmXuzPKctCUW/oLvkeFCmf6HvgUbiwT/Jfexks89WTtC3z1yWy1USbli1Gsd9/"
    "yp+hrRTfF+MbLzwqXAA8BJu/3IHmR8lgJ1JVke9TWQNI84a6hnTTIcBSqi6Bx3JYhaije2"
    "rc/3NnQJVieoChsnafgqqlfhJ7bMM5MZybEKGqOdKS5sjjMLsDa6viI/wObreqUhsBBYVi"
    "wsQ6l0a1OMWTg9bs7rJn+FpAbqoovu+rbRsFsSF8b3Zpo6zGYcTx22AIVsM2LdmKbttn6h"
    "BIHfke2AGT3Jn06v7dT9yzNfd//WRj7tu5J5BWhb/inXOHy4WbZfAoeYnmHfAthjzq6p+a"
    "Pd0cyYYdqsWl+PieKqpGCyHa4U9TgLs7OwulHXeaU8zYVw78Y/VszQa82T7lSDplnxYW61"
    "dvXr78C2nvGkI="
)
